import type { UserSearchResult } from '../types/types'

export const MOCK_USERS_SEARCH: UserSearchResult[] = [
  {
    user_id: '6b1a982e-b090-449f-811b-f6dd386cc239',
    username: 'ulyana',
    name: 'Ульяна',
    age: 26,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Обожаю готовить, смотреть сериалы и гулять с собакой. Ищу того, с кем будет комфортно.',
    city: 'Сочи',
    job: 'Реаниматолог',
    job_sphere: 'media',
    education_level: 'school',
    education_details: 'КФУ',
    subscription_tier: 'vip',
    boost_expires_at: '2026-05-05T14:04:09.719113Z',
    last_seen: '2026-05-05T11:07:09.719110Z',
    is_banned: false,
    photos: [
      'https://api.lascovo.ru/static/images/test_photos/photo_1.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_4.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_6.jpg',
    ],
    filters: {
      appearance: {
        hair: ['bob', 'short'],
        style: ['classic', 'street'],
        body: ['average'],
      },
      interests: {
        sport: ['yoga', 'gym', 'swimming', 'running'],
      },
      lifestyle: {
        pets: ['dogs'],
      },
    },
    adequacy_score: 9.9,
    match_percentage: 56,
  },
  {
    user_id: '69f480a0-e0a7-4729-b551-494487cec62b',
    username: 'nekrasova',
    name: 'Некрасова',
    age: 18,
    gender: 'female',
    relationship_goal: 'communication',
    bio: 'Активный образ жизни, бег по утрам, здоровое питание. Ищу партнера для совместных тренировок.',
    city: 'Казань',
    job: 'Маммолог',
    job_sphere: 'medicine',
    education_level: 'higher',
    education_details: 'МФТИ',
    subscription_tier: 'premium',
    boost_expires_at: '2026-05-05T14:04:09.760599Z',
    last_seen: '2026-05-05T10:26:09.760597Z',
    is_banned: false,
    photos: [
      'https://api.lascovo.ru/static/images/test_photos/photo_1.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_1.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_10.jpg',
    ],
    filters: {
      interests: {
        hobby: ['cinema', 'photo'],
      },
      appearance: {
        hair: ['bob', 'bald'],
        style: ['sporty'],
      },
      lifestyle: {
        pets: ['cats', 'dogs', 'none'],
      },
    },
    adequacy_score: 9.6,
    match_percentage: 53,
  },
  {
    user_id: 'd1d56c41-52e9-4ba4-8f21-0cbcbcf10dc5',
    username: 'praskovya29',
    name: 'Прасковья',
    age: 29,
    gender: 'female',
    relationship_goal: 'party',
    bio: 'Танцы, искусство и хорошее вино - то, что люблю. Важна эмоциональная связь.',
    city: 'Санкт-Петербург',
    job: 'Техник',
    job_sphere: 'engineering',
    education_level: 'college',
    education_details: 'НИУ ВШЭ',
    subscription_tier: 'free',
    boost_expires_at: '2026-05-05T14:04:09.753793Z',
    last_seen: '2026-05-05T10:30:09.753791Z',
    is_banned: false,
    photos: ['https://api.lascovo.ru/static/images/test_photos/photo_5.jpg'],
    filters: {
      interests: {
        hobby: ['music', 'books'],
        sport: ['gym', 'yoga', 'swimming'],
      },
      lifestyle: {
        pets: ['cats'],
        routine: ['night'],
      },
      appearance: {
        style: ['sporty'],
        hair: ['long', 'bald'],
        body: ['slim', 'average'],
      },
    },
    adequacy_score: 9.1,
    match_percentage: 51,
  },
  {
    user_id: '8700934c-c838-4163-ae5f-2df817db285d',
    username: 'praskovya18',
    name: 'Прасковья',
    age: 18,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Интроверт, домосед, люблю тишину и уют. Ценю спокойствие и взаимопонимание.',
    city: 'Москва',
    job: 'Токарь-карусельщик',
    job_sphere: 'medicine',
    education_level: 'college',
    education_details: 'МФТИ',
    subscription_tier: 'premium',
    boost_expires_at: null,
    last_seen: '2026-05-02T17:03:09.728342Z',
    is_banned: false,
    photos: [
      'https://api.lascovo.ru/static/images/test_photos/photo_5.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_5.jpg',
    ],
    filters: {
      lifestyle: {
        pets: ['cats', 'none'],
        routine: ['morning'],
      },
      interests: {
        sport: ['running'],
        hobby: ['photo', 'books', 'travel'],
      },
      appearance: {
        style: ['street'],
      },
    },
    adequacy_score: 8.3,
    match_percentage: 54,
  },
  {
    user_id: '419578a2-bddd-44a3-8a74-a879bd56ea47',
    username: 'ivanna',
    name: 'Иванна',
    age: 21,
    gender: 'female',
    relationship_goal: 'ons',
    bio: 'Обожаю спорт, книги и хорошую музыку. Ищу человека с похожими ценностями.',
    city: 'Сочи',
    job: 'Слесарь-механик',
    job_sphere: 'management',
    education_level: 'college',
    education_details: 'КФУ',
    subscription_tier: 'vip',
    boost_expires_at: null,
    last_seen: '2026-04-30T19:16:09.746535Z',
    is_banned: false,
    photos: ['https://api.lascovo.ru/static/images/test_photos/photo_6.jpg'],
    filters: {
      appearance: {
        hair: ['long', 'bob', 'bald'],
        style: ['classic', 'street'],
        body: ['slim'],
      },
      interests: {
        hobby: ['cinema'],
        sport: ['gym'],
      },
    },
    adequacy_score: 8.9,
    match_percentage: 51,
  },
  {
    user_id: '7d551821-b9e6-4716-8726-8c36ba6234e5',
    username: 'anzhela',
    name: 'Анжела',
    age: 25,
    gender: 'female',
    relationship_goal: 'communication',
    bio: 'Нравится развиваться, пробовать новое и путешествовать. Важны уважение и честность.',
    city: 'Казань',
    job: 'Шорник',
    job_sphere: 'it',
    education_level: 'school',
    education_details: 'УрФУ',
    subscription_tier: 'premium',
    boost_expires_at: null,
    last_seen: '2026-04-30T13:08:09.729734Z',
    is_banned: false,
    photos: [
      'https://api.lascovo.ru/static/images/test_photos/photo_2.jpg',
      'https://api.lascovo.ru/static/images/test_photos/photo_3.jpg',
    ],
    filters: {
      appearance: {
        hair: ['bald', 'long'],
      },
      interests: {
        sport: ['yoga', 'swimming', 'gym', 'running'],
        hobby: ['travel', 'cinema'],
      },
      lifestyle: {
        pets: ['dogs'],
      },
    },
    adequacy_score: 5.4,
    match_percentage: 56,
  },
]
