import path from 'node:path'
import fsExtra from 'fs-extra'
import { glob } from 'glob'
import { parse } from 'node-html-parser'

const cwd = process.cwd()

const inputDir = path.join(cwd, 'src', 'shared', 'assets')
const inputDirRelative = path.relative(cwd, inputDir)
const outputDir = path.join(cwd, 'public')

await fsExtra.ensureDir(outputDir)

const files = (
  await glob('**/*.svg', {
    cwd: inputDir,
  })
).sort((a, b) => a.localeCompare(b))

const shouldVerboseLog = process.argv.includes('--log=verbose')
const logVerbose = shouldVerboseLog ? console.log : () => {}

if (files.length === 0) {
  console.log(`No SVG files found in ${inputDirRelative}`)
} else {
  await generateIconFiles()
}

async function generateIconFiles() {
  const spriteFilepath = path.join(outputDir, 'sprite.svg')
  const currentSprite = await fsExtra.readFile(spriteFilepath, 'utf8').catch(() => '')

  const iconNames = files.map((file) => iconName(file))
  const spriteUpToDate = iconNames.every((name) => currentSprite.includes(`id="${name}"`))

  if (spriteUpToDate) {
    logVerbose('Icons are up to date')
    return
  }

  await generateSvgSprite({
    files,
    inputDir,
    outputPath: spriteFilepath,
  })
}

function iconName(file) {
  return file.replace(/\.svg$/, '').replace(/\\/g, '/')
}

/**
 * Creates a single SVG file that contains all the icons.
 * Every source SVG becomes a <symbol> inside the final sprite.
 */
async function generateSvgSprite({ files, inputDir, outputPath }) {
  const symbols = await Promise.all(
    files.map(async (file) => {
      const input = await fsExtra.readFile(path.join(inputDir, file), 'utf8')
      const root = parse(input)
      const svg = root.querySelector('svg')

      if (svg == null) throw new Error(`No <svg> element found in ${file}`)

      svg.tagName = 'symbol'
      svg.setAttribute('id', iconName(file))

      svg.removeAttribute('xmlns')
      svg.removeAttribute('xmlns:xlink')
      svg.removeAttribute('version')
      svg.removeAttribute('width')
      svg.removeAttribute('height')

      const innerElements = svg.querySelectorAll('*')
      innerElements.forEach((el) => {
        el.removeAttribute('fill')
        el.removeAttribute('stroke')
      })

      return svg.toString().trim()
    }),
  )

  const output = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- This file is generated by `npm run build:icons`. Do not edit manually. -->',
    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0" style="position:absolute;left:-9999px;visibility:hidden">',
    '<defs>',
    ...symbols,
    '</defs>',
    '</svg>',
    '',
  ].join('\n')

  await writeIfChanged(outputPath, output)

  console.log(`Generated sprite with ${files.length} icons at ${path.relative(cwd, outputPath)}`)
}

async function writeIfChanged(filepath, newContent) {
  const currentContent = await fsExtra.readFile(filepath, 'utf8').catch(() => '')

  if (currentContent === newContent) return false

  await fsExtra.writeFile(filepath, newContent, 'utf8')
  return true
}
