import type { UserSearchApiUser } from '@/entities/user/types/types'

export const MOCK_LIKES: UserSearchApiUser[] = [
  {
    user_id: 'like-1',
    username: 'anna_k',
    name: 'Анна',
    age: 22,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Люблю путешествия и кофе ☕',
    city: 'Москва',
    job: 'Дизайнер',
    job_sphere: 'Дизайн',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/photo_2025-12-23_22-41-09.jpg'],
    filter_option_ids: [],
    match_percentage: 87,
  },
  {
    user_id: 'like-2',
    username: 'maria_v',
    name: 'Мария',
    age: 25,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Фотограф 📸',
    city: 'Санкт-Петербург',
    job: 'Фотограф',
    job_sphere: 'Искусство',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/photo_2025-12-16_22-32-35.jpg'],
    filter_option_ids: [],
    match_percentage: 92,
  },
  {
    user_id: 'like-3',
    username: 'elena_s',
    name: 'Елена',
    age: 23,
    gender: 'female',
    relationship_goal: 'dating',
    bio: 'Танцую и рисую 🎨',
    city: 'Сочи',
    job: 'Маркетолог',
    job_sphere: 'Маркетинг',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/photo_2025-04-10_00-42-15.jpg'],
    filter_option_ids: [],
    match_percentage: 78,
  },
  {
    user_id: 'like-4',
    username: 'daria_m',
    name: 'Дарья',
    age: 21,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Студентка, люблю спорт 🏃‍♀️',
    city: 'Казань',
    job: 'Студентка',
    job_sphere: 'Образование',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/i.webp'],
    filter_option_ids: [],
    match_percentage: 85,
  },
  {
    user_id: 'like-5',
    username: 'sofia_l',
    name: 'София',
    age: 24,
    gender: 'female',
    relationship_goal: 'dating',
    bio: 'Музыка и книги 📚',
    city: 'Москва',
    job: 'Аналитик',
    job_sphere: 'IT',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/photo_2025-12-23_22-41-09.jpg'],
    filter_option_ids: [],
    match_percentage: 91,
  },
  {
    user_id: 'like-6',
    username: 'kate_p',
    name: 'Екатерина',
    age: 26,
    gender: 'female',
    relationship_goal: 'relationship',
    bio: 'Путешествия и йога 🧘‍♀️',
    city: 'Краснодар',
    job: 'HR-менеджер',
    job_sphere: 'HR',
    education_level: 'Высшее',
    education_details: 'ВУЗ',
    photos: ['/images/photo_2025-12-16_22-32-35.jpg'],
    filter_option_ids: [],
    match_percentage: 89,
  },
]
