export { fetchChatsList } from './api/chatService'
export { useChatWebSocket } from './hooks/useChatWebSocket'
export { flattenChatsPages, useChatsList } from './hooks/useChatsList'
export { CHAT_WS_EVENTS } from './lib/chatWsEvents'
export { chatsQueryKeys } from './lib/chatsQueryKeys'
export type { ChatListItem, ChatListItemDto } from './types/types'
export type { ChatMessage } from './types/message'
export type { ChatMessagesPageData, ChatOpenData, ChatWsEnvelope } from './types/chatSocket'
