export interface MockChat {
  id: string
  name: string
  age?: number
  lastMessage: string
  avatar: string
  timestamp: string
  unreadCount: number
  online?: boolean
  isTyping?: boolean
}

export const MOCK_CHATS: MockChat[] = [
  {
    id: '1',
    name: 'Lucy',
    age: 22,
    lastMessage: 'Photo',
    avatar: '/images/photo_2025-12-23_22-41-09.jpg',
    timestamp: '15:42',
    unreadCount: 3,
    online: true,
  },
  {
    id: '2',
    name: 'Мария',
    age: 24,
    lastMessage: "It's me with my friends",
    avatar: '/images/photo_2025-12-16_22-32-35.jpg',
    timestamp: 'Вчера',
    unreadCount: 0,
    online: false,
  },
  {
    id: '3',
    name: 'Елена',
    age: 26,
    lastMessage: 'Is typing...',
    avatar: '/images/photo_2025-04-10_00-42-15.jpg',
    timestamp: 'Чт',
    unreadCount: 0,
    online: true,
    isTyping: true,
  },
  {
    id: '4',
    name: 'Дарья',
    age: 21,
    lastMessage: 'Я уже на месте',
    avatar: '/images/i.webp',
    timestamp: 'Пн',
    unreadCount: 1,
    online: false,
  },
  {
    id: '5',
    name: 'София',
    age: 23,
    lastMessage: 'Скинь фотки плиз',
    avatar: '/images/photo_2025-12-23_22-41-09.jpg',
    timestamp: '10.03',
    unreadCount: 0,
    online: true,
  },
  {
    id: '6',
    name: 'Алиса',
    age: 25,
    lastMessage: 'Увидимся в 19:00?',
    avatar: '/images/photo_2025-12-16_22-32-35.jpg',
    timestamp: '14:20',
    unreadCount: 2,
    online: false,
  },
  {
    id: '7',
    name: 'Катя',
    age: 27,
    lastMessage: 'Спасибо за вчера 🙏',
    avatar: '/images/photo_2025-04-10_00-42-15.jpg',
    timestamp: '11:05',
    unreadCount: 0,
    online: true,
  },
  {
    id: '8',
    name: 'Вика',
    age: 20,
    lastMessage: 'Ок, договорились',
    avatar: '/images/i.webp',
    timestamp: 'Ср',
    unreadCount: 0,
    online: false,
  },
  {
    id: '9',
    name: 'Полина',
    age: 28,
    lastMessage: 'Кинула ссылку в профиль',
    avatar: '/images/photo_2025-12-23_22-41-09.jpg',
    timestamp: '09:12',
    unreadCount: 4,
    online: true,
  },
  {
    id: '10',
    name: 'Настя',
    age: 22,
    lastMessage: 'Ты где?',
    avatar: '/images/photo_2025-12-16_22-32-35.jpg',
    timestamp: '08:44',
    unreadCount: 0,
    online: false,
  },
  {
    id: '11',
    name: 'Оля',
    age: 24,
    lastMessage: 'Завтра на йогу идёшь?',
    avatar: '/images/photo_2025-04-10_00-42-15.jpg',
    timestamp: 'Вт',
    unreadCount: 1,
    online: true,
  },
  {
    id: '12',
    name: 'Ира',
    age: 26,
    lastMessage: 'Фото с праздника просто огонь',
    avatar: '/images/photo_2025-12-23_22-41-09.jpg',
    timestamp: 'Пт',
    unreadCount: 0,
    online: false,
  },
  {
    id: '13',
    name: 'Мила',
    age: 23,
    lastMessage: 'Напиши как освободишься',
    avatar: '/images/i.webp',
    timestamp: '20:01',
    unreadCount: 6,
    online: true,
  },
  {
    id: '14',
    name: 'Света',
    age: 29,
    lastMessage: 'Да, я за!',
    avatar: '/images/photo_2025-12-16_22-32-35.jpg',
    timestamp: 'Сб',
    unreadCount: 0,
    online: false,
  },
  {
    id: '15',
    name: 'Женя',
    age: 21,
    lastMessage: 'Лол, согласна',
    avatar: '/images/photo_2025-04-10_00-42-15.jpg',
    timestamp: 'Вс',
    unreadCount: 0,
    online: true,
  },
]
