version: '3.0'

x-app-env-file: &app-env-file
  env_file:
    - ./backend/.env
  environment:
    YAMMY_ENV: production
    HF_HOME: /app/model_cache

x-backend-build: &backend-build
  context: ./backend
  dockerfile: Dockerfile

x-backend-image: &backend-image yammy-backend:local


services:

  redis:
    image: redis:7
    container_name: redis-store
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch-store
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: *backend-image
    container_name: taskiq-worker
    command: taskiq worker app.core.clients.taskiq_client:broker --fs-discover --no-parse
    <<: *app-env-file
    depends_on:
      redis: { condition: service_started }
      db: { condition: service_healthy }
    networks:
      - app-network
    volumes:
      - ./static:/app/static

  scheduler:
    image: *backend-image
    container_name: taskiq-scheduler
    command: taskiq scheduler app.core.clients.taskiq_client:scheduler
    <<: *app-env-file
    depends_on:
      redis: { condition: service_started }
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db-store
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres123 -U postgres123"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  app:
    image: *backend-image
    build: *backend-build
    container_name: app-store
    <<: *app-env-file
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./hf_model_cache:/app/model_cache

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  elasticsearch-data:
  prometheus-data:
  grafana-data:
